### ISSUE TITLE
Add rel="noreferrer"  to blank targets

### ISSUE THREAD

**Issue by codecakes** [Xcov19/mycovidconnect#118]
**Describe the bug**
src\components\Footer.jsx:16 and src\components\Footer.jsx:26
Not Using target="_blank" without rel="noreferrer" is a security risk

See why: https://mathiasbynens.github.io/rel-noopener/
Refer to  https://github.com/Xcov19/mycovidconnect/pull/113#pullrequestreview-511171752

**To Reproduce**
Run locally or the test link; 
Browse the src code: src\components\Footer.jsx:16 and src\components\Footer.jsx:26

**Expected behavior**
Blank targets shouldn't have a referrer.
Mitigation as described here: https://mathiasbynens.github.io/rel-noopener/

**Comment by sesamechicken** [comment]
I’ll take it if it’s cool with you.
