### ISSUE TITLE
Lint App.css correctly

### ISSUE THREAD

**Issue by codecakes** [Xcov19/mycovidconnect#126]
Update src/App.css. See below

   2:2  ✖  Expected indentation of 2 spaces   indentation
   3:2  ✖  Expected indentation of 2 spaces   indentation
   7:2  ✖  Expected indentation of 2 spaces   indentation
   8:2  ✖  Expected indentation of 2 spaces   indentation
   9:2  ✖  Expected indentation of 2 spaces   indentation
  10:2  ✖  Expected indentation of 2 spaces   indentation
  20:2  ✖  Expected indentation of 2 spaces   indentation
  21:2  ✖  Expected indentation of 2 spaces   indentation
  22:2  ✖  Expected indentation of 2 spaces   indentation
  23:2  ✖  Expected indentation of 2 spaces   indentation
  27:2  ✖  Expected indentation of 2 spaces   indentation
  28:2  ✖  Expected indentation of 2 spaces   indentation
  29:2  ✖  Expected indentation of 2 spaces   indentation
  39:2  ✖  Expected indentation of 2 spaces   indentation
  40:2  ✖  Expected indentation of 2 spaces   indentation
  41:2  ✖  Expected indentation of 2 spaces   indentation
  45:2  ✖  Expected indentation of 2 spaces   indentation
  46:2  ✖  Expected indentation of 2 spaces   indentation
  47:2  ✖  Expected indentation of 2 spaces   indentation
  48:2  ✖  Expected indentation of 2 spaces   indentation
  52:2  ✖  Expected indentation of 2 spaces   indentation
  53:2  ✖  Expected indentation of 2 spaces   indentation
  54:2  ✖  Expected indentation of 2 spaces   indentation
  58:2  ✖  Expected indentation of 2 spaces   indentation
  59:2  ✖  Expected indentation of 2 spaces   indentation
  60:2  ✖  Expected indentation of 2 spaces   indentation
  61:2  ✖  Expected indentation of 2 spaces   indentation
  62:2  ✖  Expected indentation of 2 spaces   indentation
  66:2  ✖  Expected indentation of 2 spaces   indentation
  67:2  ✖  Expected indentation of 2 spaces   indentation
  68:2  ✖  Expected indentation of 2 spaces   indentation
  69:2  ✖  Expected indentation of 2 spaces   indentation
  70:2  ✖  Expected indentation of 2 spaces   indentation
  71:2  ✖  Expected indentation of 2 spaces   indentation
  72:2  ✖  Expected indentation of 2 spaces   indentation
  73:2  ✖  Expected indentation of 2 spaces   indentation
  77:2  ✖  Expected indentation of 2 spaces   indentation
  78:2  ✖  Expected indentation of 2 spaces   indentation
  82:2  ✖  Expected indentation of 2 spaces   indentation
  86:2  ✖  Expected indentation of 2 spaces   indentation
  87:2  ✖  Expected indentation of 2 spaces   indentation
  88:2  ✖  Expected indentation of 2 spaces   indentation
  92:2  ✖  Expected indentation of 2 spaces   indentation
  93:2  ✖  Expected indentation of 2 spaces   indentation
  94:2  ✖  Expected indentation of 2 spaces   indentation
  98:2  ✖  Expected indentation of 2 spaces   indentation
  99:2  ✖  Expected indentation of 2 spaces   indentation
 100:2  ✖  Expected indentation of 2 spaces   indentation
 101:2  ✖  Expected indentation of 2 spaces   indentation
 102:2  ✖  Expected indentation of 2 spaces   indentation
 103:2  ✖  Expected indentation of 2 spaces   indentation
 104:2  ✖  Expected indentation of 2 spaces   indentation
 108:2  ✖  Expected indentation of 2 spaces   indentation
 109:2  ✖  Expected indentation of 2 spaces   indentation
 110:2  ✖  Expected indentation of 2 spaces   indentation
 111:2  ✖  Expected indentation of 2 spaces   indentation
 112:2  ✖  Expected indentation of 2 spaces   indentation
 116:2  ✖  Expected indentation of 2 spaces   indentation
 117:2  ✖  Expected indentation of 2 spaces   indentation
 121:2  ✖  Expected indentation of 2 spaces   indentation
 122:2  ✖  Expected indentation of 2 spaces   indentation
 126:2  ✖  Expected indentation of 2 spaces   indentation
 127:2  ✖  Expected indentation of 2 spaces   indentation
 128:2  ✖  Expected indentation of 2 spaces   indentation
 132:2  ✖  Expected indentation of 2 spaces   indentation
 133:2  ✖  Expected indentation of 2 spaces   indentation
 143:2  ✖  Expected indentation of 2 spaces   indentation
 144:2  ✖  Expected indentation of 2 spaces   indentation
 145:2  ✖  Expected indentation of 2 spaces   indentation
 149:2  ✖  Expected indentation of 2 spaces   indentation
 150:2  ✖  Expected indentation of 2 spaces   indentation
 151:2  ✖  Expected indentation of 2 spaces   indentation
 161:2  ✖  Expected indentation of 2 spaces   indentation
 162:2  ✖  Expected indentation of 2 spaces   indentation
 163:2  ✖  Expected indentation of 2 spaces   indentation
 164:2  ✖  Expected indentation of 2 spaces   indentation
 165:2  ✖  Expected indentation of 2 spaces   indentation
 166:2  ✖  Expected indentation of 2 spaces   indentation
 167:2  ✖  Expected indentation of 2 spaces   indentation
 168:2  ✖  Expected indentation of 2 spaces   indentation
 169:2  ✖  Expected indentation of 2 spaces   indentation
 170:2  ✖  Expected indentation of 2 spaces   indentation
 171:2  ✖  Expected indentation of 2 spaces   indentation
 172:2  ✖  Expected indentation of 2 spaces   indentation
 176:2  ✖  Expected indentation of 2 spaces   indentation
 177:2  ✖  Expected indentation of 2 spaces   indentation
 178:2  ✖  Expected indentation of 2 spaces   indentation
 179:2  ✖  Expected indentation of 2 spaces   indentation
 180:2  ✖  Expected indentation of 2 spaces   indentation
 181:2  ✖  Expected indentation of 2 spaces   indentation
 185:2  ✖  Expected indentation of 2 spaces   indentation
 186:2  ✖  Expected indentation of 2 spaces   indentation
 187:2  ✖  Expected indentation of 2 spaces   indentation
 188:2  ✖  Expected indentation of 2 spaces   indentation
 189:2  ✖  Expected indentation of 2 spaces   indentation
 190:2  ✖  Expected indentation of 2 spaces   indentation
 194:2  ✖  Expected indentation of 2 spaces   indentation
 195:2  ✖  Expected indentation of 2 spaces   indentation
 196:2  ✖  Expected indentation of 2 spaces   indentation
 197:2  ✖  Expected indentation of 2 spaces   indentation
 198:2  ✖  Expected indentation of 2 spaces   indentation
 199:2  ✖  Expected indentation of 2 spaces   indentation
 200:2  ✖  Expected indentation of 2 spaces   indentation
 201:2  ✖  Expected indentation of 2 spaces   indentation
 205:2  ✖  Expected indentation of 2 spaces   indentation
 206:2  ✖  Expected indentation of 2 spaces   indentation
 207:2  ✖  Expected indentation of 2 spaces   indentation
 208:2  ✖  Expected indentation of 2 spaces   indentation
 209:2  ✖  Expected indentation of 2 spaces   indentation
 210:2  ✖  Expected indentation of 2 spaces   indentation
 211:2  ✖  Expected indentation of 2 spaces   indentation
 212:2  ✖  Expected indentation of 2 spaces   indentation
 213:2  ✖  Expected indentation of 2 spaces   indentation
 214:2  ✖  Expected indentation of 2 spaces   indentation
 215:2  ✖  Expected indentation of 2 spaces   indentation
 219:2  ✖  Expected indentation of 2 spaces   indentation
 223:2  ✖  Expected indentation of 2 spaces   indentation
 224:2  ✖  Expected indentation of 2 spaces   indentation
 225:2  ✖  Expected indentation of 2 spaces   indentation
 226:2  ✖  Expected indentation of 2 spaces   indentation
 227:2  ✖  Expected indentation of 2 spaces   indentation
 228:2  ✖  Expected indentation of 2 spaces   indentation
 229:2  ✖  Expected indentation of 2 spaces   indentation
 233:2  ✖  Expected indentation of 2 spaces   indentation
 234:2  ✖  Expected indentation of 2 spaces   indentation
 235:2  ✖  Expected indentation of 2 spaces   indentation
 236:2  ✖  Expected indentation of 2 spaces   indentation
 237:2  ✖  Expected indentation of 2 spaces   indentation
 238:2  ✖  Expected indentation of 2 spaces   indentation
 239:2  ✖  Expected indentation of 2 spaces   indentation
 249:2  ✖  Expected indentation of 2 spaces   indentation
 250:2  ✖  Expected indentation of 2 spaces   indentation
 251:2  ✖  Expected indentation of 2 spaces   indentation
 252:2  ✖  Expected indentation of 2 spaces   indentation
 253:2  ✖  Expected indentation of 2 spaces   indentation
 254:2  ✖  Expected indentation of 2 spaces   indentation
 258:2  ✖  Expected indentation of 2 spaces   indentation
 259:2  ✖  Expected indentation of 2 spaces   indentation
 260:2  ✖  Expected indentation of 2 spaces   indentation
 261:2  ✖  Expected indentation of 2 spaces   indentation
 262:2  ✖  Expected indentation of 2 spaces   indentation
 263:2  ✖  Expected indentation of 2 spaces   indentation
 264:2  ✖  Expected indentation of 2 spaces   indentation
 268:2  ✖  Expected indentation of 2 spaces   indentation
 269:2  ✖  Expected indentation of 2 spaces   indentation
 270:2  ✖  Expected indentation of 2 spaces   indentation
 271:2  ✖  Expected indentation of 2 spaces   indentation
 272:2  ✖  Expected indentation of 2 spaces   indentation
 273:2  ✖  Expected indentation of 2 spaces   indentation
 274:2  ✖  Expected indentation of 2 spaces   indentation
 278:2  ✖  Expected indentation of 2 spaces   indentation
 279:2  ✖  Expected indentation of 2 spaces   indentation
 280:2  ✖  Expected indentation of 2 spaces   indentation
 281:2  ✖  Expected indentation of 2 spaces   indentation
 285:2  ✖  Expected indentation of 2 spaces   indentation
 286:2  ✖  Expected indentation of 2 spaces   indentation
 287:2  ✖  Expected indentation of 2 spaces   indentation
 288:2  ✖  Expected indentation of 2 spaces   indentation
 289:2  ✖  Expected indentation of 2 spaces   indentation
 290:2  ✖  Expected indentation of 2 spaces   indentation
 291:2  ✖  Expected indentation of 2 spaces   indentation
 295:2  ✖  Expected indentation of 2 spaces   indentation
 296:2  ✖  Expected indentation of 2 spaces   indentation
 297:2  ✖  Expected indentation of 2 spaces   indentation
 298:2  ✖  Expected indentation of 2 spaces   indentation
 299:2  ✖  Expected indentation of 2 spaces   indentation
 303:2  ✖  Expected indentation of 2 spaces   indentation
 304:2  ✖  Expected indentation of 2 spaces   indentation
 305:2  ✖  Expected indentation of 2 spaces   indentation
 306:2  ✖  Expected indentation of 2 spaces   indentation
 310:2  ✖  Expected indentation of 2 spaces   indentation
 311:2  ✖  Expected indentation of 2 spaces   indentation
 312:2  ✖  Expected indentation of 2 spaces   indentation
 313:2  ✖  Expected indentation of 2 spaces   indentation
 314:2  ✖  Expected indentation of 2 spaces   indentation
 315:2  ✖  Expected indentation of 2 spaces   indentation
 316:2  ✖  Expected indentation of 2 spaces   indentation
 320:2  ✖  Expected indentation of 2 spaces   indentation
 321:2  ✖  Expected indentation of 2 spaces   indentation
 322:2  ✖  Expected indentation of 2 spaces   indentation
 323:2  ✖  Expected indentation of 2 spaces   indentation
 324:2  ✖  Expected indentation of 2 spaces   indentation
 328:2  ✖  Expected indentation of 2 spaces   indentation
 329:2  ✖  Expected indentation of 2 spaces   indentation
 330:2  ✖  Expected indentation of 2 spaces   indentation
 334:2  ✖  Expected indentation of 2 spaces   indentation
 335:2  ✖  Expected indentation of 2 spaces   indentation
 336:2  ✖  Expected indentation of 2 spaces   indentation
 337:2  ✖  Expected indentation of 2 spaces   indentation
 338:2  ✖  Expected indentation of 2 spaces   indentation
 339:2  ✖  Expected indentation of 2 spaces   indentation
 340:2  ✖  Expected indentation of 2 spaces   indentation
 341:2  ✖  Expected indentation of 2 spaces   indentation
 342:2  ✖  Expected indentation of 2 spaces   indentation
 346:2  ✖  Expected indentation of 2 spaces   indentation
 347:2  ✖  Expected indentation of 2 spaces   indentation
 348:2  ✖  Expected indentation of 2 spaces   indentation
 349:2  ✖  Expected indentation of 2 spaces   indentation
 350:2  ✖  Expected indentation of 2 spaces   indentation
 351:2  ✖  Expected indentation of 2 spaces   indentation
 352:2  ✖  Expected indentation of 2 spaces   indentation
 356:2  ✖  Expected indentation of 2 spaces   indentation
 357:2  ✖  Expected indentation of 2 spaces   indentation
 358:2  ✖  Expected indentation of 2 spaces   indentation
 359:2  ✖  Expected indentation of 2 spaces   indentation
 360:2  ✖  Expected indentation of 2 spaces   indentation
 361:2  ✖  Expected indentation of 2 spaces   indentation
 366:2  ✖  Expected indentation of 2 spaces   indentation
 367:2  ✖  Expected indentation of 2 spaces   indentation
 368:2  ✖  Expected indentation of 2 spaces   indentation
 369:2  ✖  Expected indentation of 2 spaces   indentation
 370:2  ✖  Expected indentation of 2 spaces   indentation
 371:2  ✖  Expected indentation of 2 spaces   indentation
 372:2  ✖  Expected indentation of 2 spaces   indentation
 373:2  ✖  Expected indentation of 2 spaces   indentation
 377:2  ✖  Expected indentation of 2 spaces   indentation
 382:2  ✖  Expected indentation of 2 spaces   indentation
 383:2  ✖  Expected indentation of 2 spaces   indentation
 384:2  ✖  Expected indentation of 2 spaces   indentation
 388:2  ✖  Expected indentation of 2 spaces   indentation
 389:2  ✖  Expected indentation of 2 spaces   indentation
 390:2  ✖  Expected indentation of 2 spaces   indentation
 391:2  ✖  Expected indentation of 2 spaces   indentation
 395:2  ✖  Expected indentation of 2 spaces   indentation
 396:2  ✖  Expected indentation of 2 spaces   indentation
 397:2  ✖  Expected indentation of 2 spaces   indentation
 398:2  ✖  Expected indentation of 2 spaces   indentation
 399:2  ✖  Expected indentation of 2 spaces   indentation
 403:2  ✖  Expected indentation of 2 spaces   indentation
 404:2  ✖  Expected indentation of 2 spaces   indentation
 405:2  ✖  Expected indentation of 2 spaces   indentation
 406:2  ✖  Expected indentation of 2 spaces   indentation
 407:2  ✖  Expected indentation of 2 spaces   indentation
 408:2  ✖  Expected indentation of 2 spaces   indentation
 409:2  ✖  Expected indentation of 2 spaces   indentation
 410:2  ✖  Expected indentation of 2 spaces   indentation
 411:2  ✖  Expected indentation of 2 spaces   indentation
 415:2  ✖  Expected indentation of 2 spaces   indentation
 416:2  ✖  Expected indentation of 2 spaces   indentation
 417:2  ✖  Expected indentation of 2 spaces   indentation
 418:2  ✖  Expected indentation of 2 spaces   indentation
 419:2  ✖  Expected indentation of 2 spaces   indentation
 420:2  ✖  Expected indentation of 2 spaces   indentation
 421:2  ✖  Expected indentation of 2 spaces   indentation
 422:2  ✖  Expected indentation of 2 spaces   indentation
 423:2  ✖  Expected indentation of 2 spaces   indentation
 424:2  ✖  Expected indentation of 2 spaces   indentation
 425:2  ✖  Expected indentation of 2 spaces   indentation
 426:2  ✖  Expected indentation of 2 spaces   indentation
 427:2  ✖  Expected indentation of 2 spaces   indentation
 428:2  ✖  Expected indentation of 2 spaces   indentation
 432:2  ✖  Expected indentation of 2 spaces   indentation
 433:2  ✖  Expected indentation of 2 spaces   indentation
 434:2  ✖  Expected indentation of 2 spaces   indentation
 435:2  ✖  Expected indentation of 2 spaces   indentation
 436:2  ✖  Expected indentation of 2 spaces   indentation
 437:2  ✖  Expected indentation of 2 spaces   indentation
 438:2  ✖  Expected indentation of 2 spaces   indentation
 439:2  ✖  Expected indentation of 2 spaces   indentation
 443:2  ✖  Expected indentation of 2 spaces   indentation
 444:2  ✖  Expected indentation of 2 spaces   indentation
 448:2  ✖  Expected indentation of 2 spaces   indentation
 449:2  ✖  Expected indentation of 2 spaces   indentation
 450:2  ✖  Expected indentation of 2 spaces   indentation
 451:2  ✖  Expected indentation of 2 spaces   indentation
 452:2  ✖  Expected indentation of 2 spaces   indentation
 453:2  ✖  Expected indentation of 2 spaces   indentation

**Comment by AmeyaPhadnis-2019H1030012G** [comment]
Can I work on this, I am new to the open-source community and looking forward to opportunities to contribute. Thanks in advance!

**Comment by L-crypt** [comment]
I am not understanding about the issue. Kindly give a brief about the error.

**Comment by shivarajloni** [comment]
Hey! can i contribute, i am new to Open-source and looking for first-timer contribution

**Comment by L-crypt** [comment]
Can I work on this issue?

**Comment by ajitesh20** [comment]
Can I work on this issue, I am new to open-source
