### ISSUE TITLE
Search Map Pt 2 - Results

### ISSUE THREAD

**Issue by codecakes** [Xcov19/mycovidconnect#13]
USE Smart Commits:
For all git commits relevant to all dependent tasks upto this story, use this commit format:
"MYC-6 #comment <YOUR_COMMENTS>"

After the user hits ‘SOS’ button, user should be able to see healthcare facilities available in 50 KM vicinity.

User should be able to see a map with available hospitals options on it.

User should be able to navigate and see the details on the left such as point of contact, contact number, travel time, direction per results. Refer to the mock

See zip file: 
[Xcov19_v1.zip](https://github.com/Xcov19/mycovidconnect/files/5124338/Xcov19_v1.zip)

**Comment by codecakes** [comment]
@GeekySankar ping me here when u start working on google map api;

**Comment by codecakes** [comment]
@GeekySankar use this format while committing on maps api;

"MYC-36 #comment <YOUR_COMMENTS>"

And 

"MYC-6 #comment <YOUR_COMMENTS>"

for the rest of the search feature commits

**Comment by codecakes** [comment]
@GeekySankar 
mockup: 
![image](https://user-images.githubusercontent.com/7066977/91561473-4eb3f880-e959-11ea-9da0-a1a0b6b340ea.png)

Mockup zip for search results: 
[XCOV19_First_Look.xd.zip](https://github.com/Xcov19/mycovidconnect/files/5142056/XCOV19_First_Look.xd.zip)

**Comment by GeekySankar** [comment]
<img width="1765" alt="Screenshot 2020-08-29 at 12 39 43 AM" src="https://user-images.githubusercontent.com/43127344/91606752-4925d500-e990-11ea-8ca1-3675e8b88fc5.png">
