### ISSUE TITLE
Error while running react scripts

### ISSUE THREAD

**Issue by premalrupnur** [Xcov19/mycovidconnect#133]
I am not able to run react scripts don't know why I am getting error

**Screenshots**
![Screenshot (268)](https://user-images.githubusercontent.com/55614144/99092917-d378ef00-25f7-11eb-8e2f-7dd95cc026ce.png)

**Desktop :**
 - OS: Windows 10
 - Browser : Chrome
 

Also I tried rebuilding the docker image but now I am not able to build it too

**Screenshots**
![Screenshot (269)](https://user-images.githubusercontent.com/55614144/99100080-5488b400-2601-11eb-8d27-8a749fe368d4.png)

**Comment by codecakes** [comment]
@premalrupnur paste the commands you followed for each of the steps to be reproduced.

**Comment by premalrupnur** [comment]
1.`docker-compose -f "docker-compose.yml" up -d --build`
2.`npm start`

**Comment by codecakes** [comment]
> 1.`docker-compose -f "docker-compose.yml" up -d --build`
> 2.`npm start`

You can either run 1 or 2; See Dockerfile  more info on what it involves to run node server app;
If you go with step 2, see docker-compose.yaml file for whatelse is needed.

I am not sure why you are running `npn start` if you have run docker command already. you should be able to access the site from your localhost.

If you have docker engine and docker compose installed then it should be accessible from localhost:9119

**Comment by codecakes** [comment]
> I am not able to run react scripts don't know why I am getting error
> 
> **Screenshots**
> ![Screenshot (268)](https://user-images.githubusercontent.com/55614144/99092917-d378ef00-25f7-11eb-8e2f-7dd95cc026ce.png)
> 
> **Desktop :**
> 
>     * OS: Windows 10
> 
>     * Browser : Chrome
> 
>
When you did `npm start` ; did you first install the package dependencies first?

**Comment by premalrupnur** [comment]
I removed these two lines `COPY startup.sh ./
RUN ./startup.sh` from startup.sh  and it worked

**Comment by premalrupnur** [comment]
But why aren't the necessary react scripts installed so that I can run .jsx files because each time I would make change to jsx files I would have to run the whole container to test the changes

**Comment by codecakes** [comment]
> But why aren't the necessary react scripts installed so that I can run .jsx files because each time I would make change to jsx files I would have to run the whole container to test the changes

update your local master and merge to your branch;
check package.json; everything that is there will be installed on container instance as well.
Where can you see if the necessary react scripts are not installed?

You don't need to run the whole container again. 
It should reload.

**Comment by premalrupnur** [comment]
> You don't need to run the whole container again.
> It should reload.
 
No it isn't automatically reloading

**Comment by premalrupnur** [comment]
Actually what I think is that auto reload would work after npm start is executed in which I am receiving an error so I suspect necessary scripts aren't installed with respect to error thrown

**Comment by premalrupnur** [comment]
> > I am not able to run react scripts don't know why I am getting error
> > **Screenshots**
> > ![Screenshot (268)](https://user-images.githubusercontent.com/55614144/99092917-d378ef00-25f7-11eb-8e2f-7dd95cc026ce.png)

> When you did `npm start` ; did you first install the package dependencies first?
Running docker image don't install the required packages??? I mean do I need to run package.json explicitly to installl dependencies

**Comment by premalrupnur** [comment]
> Where can you see if the necessary react scripts are not installed?

Actually the node_modules folder is empty so I suspect there had been some error while installation of dependencies

**Comment by codecakes** [comment]
> > > I am not able to run react scripts don't know why I am getting error
> > > **Screenshots**
> > > ![Screenshot (268)](https://user-images.githubusercontent.com/55614144/99092917-d378ef00-25f7-11eb-8e2f-7dd95cc026ce.png)
> 
> > When you did `npm start` ; did you first install the package dependencies first?
> 
> Running docker image don't install the required packages??? I mean do I need to run package.json explicitly to install dependencies

No you don't; you are unable to see reload because polling is not enabled; ive enabled in the cloud env

**Comment by premalrupnur** [comment]
I tried on gitpod I faced the same problem

**Comment by codecakes** [comment]
> I tried on gitpod I faced the same problem

try after 5mins
