### ISSUE TITLE
Not able to push my changes 

### ISSUE THREAD

**Issue by premalrupnur** [Xcov19/mycovidconnect#149]
**Describe the bug**
When I use the command git push it says the access is denied below I'm attaching the image 

**Screenshots**
![Screenshot (459)](https://user-images.githubusercontent.com/55614144/102479021-591f0d00-4084-11eb-8719-4f8e2fe84e54.png)

**Desktop (please complete the following information):**
 - OS: Windows

**Comment by codecakes** [comment]
Try visiting this link: https://github.com/Xcov19/mycovidconnect/invitations ; you should be added now and be able to make a PR
