### ISSUE TITLE
Create humans.txt

### ISSUE THREAD

**Issue by codecakes** [Xcov19/mycovidconnect#220]
**Is your feature request related to a problem? Please describe.**
See the motivation behind the issue: https://humanstxt.org/

**Describe the solution you'd like**
Add /humans.txt that loads a static asset .txt file

**Additional context**
Add the following in the txt:

TEAM

[Add here All the contributors listed]
____________

How to Contribute:

[Redirect to the repository ReadMe link]

___________

TECHNOLOGIES 

[List the the stack and tools used to develop this project here]

**Comment by isayakmondal** [comment]
If this is still open I would like to take up this issue.
