### ISSUE TITLE
Add custom snippet for badge at end of footer

### ISSUE THREAD

**Issue by codecakes** [Xcov19/mycovidconnect#225]
At the very end of xpath `//*[@id="root"]/footer/div/div[2]/div[2]` which is for class `media-links` add another div tag with class `third-row` right after `second-row` with following snippet for inner html:

```html5
<a href="https://simpleanalytics.com/mycovidconnect.com?utm_source=mycovidconnect.com&utm_content=badge" referrerpolicy="origin" target="_blank"><img src="https://simpleanalyticsbadge.com/mycovidconnect.com" loading="lazy" referrerpolicy="no-referrer" crossorigin="anonymous" /></a>
```

**Comment by himadri2110** [comment]
Hey,

Can I take up this issue?

**Comment by codecakes** [comment]
> Hey,
> 
> Can I take up this issue?

@himadri2110 Thanks!
