### ISSUE TITLE
@codecakes Outline and refine Docker setup and add documentation and Gotchas steps;

### ISSUE THREAD

**Issue by codecakes** [Xcov19/mycovidconnect#242]
_Originally posted by @jayeclark in https://github.com/Xcov19/mycovidconnect/issues/233#issuecomment-987194703_

First timers to the project get confused when running the project. It is better to document and outline which **scopes** of the project they can run locally (for now)

Documentation is required to limit functionality and explicitly mention it:

- [x] The contributor tries to run normally with docker but need to scope out what things will work on local. For instance, trying to login won't work. For that you need to setup your own auth0 account, for web client only and register a client. This will be your own client. Their starter tutorial for this should suffice in setting up the client and using that instead of our .env vars;
- [x] react-scripts not found. Is create-react even installed locally? Try `npm install` first
- [ ] Installing with `npm install` throws error: There is a peer dependency issue with jest module that can be fixed by installing @types/jest with the right version.

Multiple PRs accpeted to close this issue;

**Comment by codecakes** [comment]
> * Installing with `npm install` throws error: There is a peer dependency issue with jest module that can be fixed by installing @types/jest with the right version.

@jayeclark  Did you come across this issue

**Comment by jayeclark** [comment]
Yes. Installing dependencies with `yarn install`, or installing with `npm install --force` both solved the issue. I didn't spend any time trying to figure out the right version to resolve the conflict because I wasn't working with the tests.

**Comment by codecakes** [comment]
Try locking to latest version here https://www.npmjs.com/package/@types/jest and see if `npm i --save-dev` works; if it does, no need to force it and you can update that version in package

**Comment by jayeclark** [comment]
Yep, that worked. I'm going to add that in another commit.
