### ISSUE TITLE
Fibers package crashes docker build

### ISSUE THREAD

**Issue by olamilekanogunbanjo** [Xcov19/mycovidconnect#284]
While running the docker build command the build crashes.

**To Reproduce**
1. Run `docker-compose -f "docker-compose.yml" up -d --build` in the terminal.

**Expected behavior**
The build fails and error is displayed in the terminal.

**Screenshots**
<img width="784" alt="Screenshot 2022-08-20 at 19 48 36" src="https://user-images.githubusercontent.com/39389241/185755436-3f0270f6-fc26-42f3-bb26-227cbac62175.png">

**Desktop (please complete the following information):**
 - OS: [Mac]
 - Node Version [v18.7.0]

**Comment by codecakes** [comment]
https://www.npmjs.com/package/fibers
This is not supported anymore. You can remove this and retry. Raise a pr
