### ISSUE TITLE
update site logo. clicking on  it should take user back to home page;

### ISSUE THREAD

**Issue by codecakes** [Xcov19/mycovidconnect#68]
take updated logo from neha;

**Comment by batistaDev1113** [comment]
Hi @codecakes !  I would like to work on this issue if possible!

Thanks

**Comment by codecakes** [comment]
hi @batistaDev1113 lookout for this space tomorrow and you'll get an updated logo here to attach on home page;

**Comment by batistaDev1113** [comment]
Thank you!  I will be on the lookout for it :-)

**Comment by sumana-19** [comment]
Hi @codecakes I'd like to work on this issue. Could you assign this to me, please?

**Comment by codecakes** [comment]
Here is the link for the logo: https://xcov19-assets.s3-ap-southeast-1.amazonaws.com/XCOV19+Logo.png

Clicking on this logo should take user back to home page;

**Comment by batistaDev1113** [comment]
Thank you for providing it!  I will get on this and make the pull request once is done!

**Comment by rahulbhatt1899** [comment]
Hey, 
Could I work on this issue?

**Comment by batistaDev1113** [comment]
Hi @codecakes ,

The PR is already executed.  Let me know if you have any questions!

Thank you!

**Comment by moody2times** [comment]
Hello there,
I see this issue is still open. Can I work on it?

**Comment by moody2times** [comment]
Hello there,
I see this issue is still open. Can I work on it?
