### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by codecakes** [Xcov19/mycovidconnect#72]
update read me so that first timers know how to setup the pre requisites and run the docker command in order to start serving site on localhost;

**Comment by heftymouse** [comment]
Hi, can I please give this a try for Hacktoberfest?

**Comment by codecakes** [comment]
> Hi, can I please give this a try for Hacktoberfest, if it's still open?

Hi @heftymouse pls look at the README and suggest changes in a separate PR if you think there's scope for improvement.thanks!
