### ISSUE TITLE
Update the README file

### ISSUE THREAD

**Issue by codecakes** [Xcov19/mycovidconnect#76]
Follow this format:

- Project name: Your project’s name is the first thing people will see upon scrolling down to your README, and is included upon creation of your README file.

- Description: A description of your project follows. A good description is clear, short, and to the point. Describe the importance of your project, and what it does.

- Table of Contents: Optionally, include a table of contents in order to allow other people to quickly navigate especially long or detailed READMEs.

- Installation: Installation is the next section in an effective README. Tell other users how to install your project locally. Optionally, include a gif to make the process even more clear for other people.

- Usage: The next section is usage, in which you instruct other people on how to use your project after they’ve installed it. This would also be a good place to include screenshots of your project in action.

Contributing: Link to a file in project root called `CONTRIBUTING.md`

Credits: Include a section for credits in order to highlight and link to the authors of your project.

Document the process of the web service flow in the readme as well.

**Comment by MEME-MAN234** [comment]
Can I take this for my Hacktoberfest?

**Comment by codecakes** [comment]
Hi @MEME-MAN234 yes. feel free to throw any questions if you have

**Comment by MEME-MAN234** [comment]
Thanks :) Can I know what this app does? I would like to present it in the README

**Comment by codecakes** [comment]
> Thanks :) Can I know what this app does? I would like to present it in the README

Sure, see this: https://forum.mycovidconnect.com/d/2-about-xcov19-rapid-action-patient-dispatch-solution

**Comment by MEME-MAN234** [comment]
> > Thanks :) Can I know what this app does? I would like to present it in the README
> 
> Sure, see this: https://forum.mycovidconnect.com/d/2-about-xcov19-rapid-action-patient-dispatch-solution

Thanks!

**Comment by MEME-MAN234** [comment]
Please review my pull request :)

**Comment by manasi999** [comment]
hello @codecakes can i contribute to this issue for my hactober fest?

**Comment by xxKeefer** [comment]
looks like some one is alrweady on this but i would also bee happy to help
