### ISSUE TITLE
Fix DepShield link

### ISSUE THREAD

**Issue by codecakes** [Xcov19/mycovidconnect#86]
**Describe the bug**
The Readme file show the Depshield badge link. It is broken because we have not described the repository owner and repo name.

FIX: It can be updated and the badge will work if the link is updated to:

```markdown
[![DepShield Badge](https://depshield.sonatype.org/badges/Xcov19/mycovidconnect/depshield.svg)](https://depshield.github.io)
```

**To Reproduce**
See the Readme.  Or
1. Clone the repo
2. Open the readme file in a markdown readable IDE.

**Expected behavior**
The actual DepShield badge should show.

**Additional context**
This is how it should look: https://github.com/Xcov19/mycovidconnect/blob/codecakes-patch-4-fix-sonatype-badge-shield/README.md

**Comment by sumeetp4** [comment]
I would like to take up this
